### ISSUE TITLE
Darstellung der Bugs

### ISSUE THREAD

**Issue by Avagenzo** [MoritzKemp/bugtracker-mwe#2]
Möglichst minimal. Anzeige von maximal 5 Bugs. Folgender inhalt:

1. ID
2. Titel
3. Kurzbeschreibung
4. Bug-Ersteller
5. Zustand
6. Einstellzeit

**Comment by MoritzKemp** [comment]
Neue Darstellung in einer Tabelle implementiert und das Sortieren nach dem Status ermöglicht.

Weitere Schritte wären eine Detailansicht für Bugs, damit auch längere Beschreibungen möglich sind.

**Comment by MoritzKemp** [comment]
Weitesgehend abgeschlossen.
